name: Blog Posts Workflow
on:
  schedule:
    - cron: '0 17 * * *' # Runs at 00:00 Vietnam time
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://yourblog.com/feed.xml" # Replace with your blog's RSS feed
          max_post_count: "4"
