name: Waka Readme
on:
  schedule: [{ cron: "0 17 * * *" }]
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_TIMEZONE: "True"
